name: wazo-cel-plugin
namespace: official
version: 2.5.0
author: Wazo Communication inc.
display_name: CEL API
min_wazo_version: 25.01
tags:
  - api
  - call_logs
  - cel
  - http
homepage: http://wazo-platform.org
